useTabs: false
printWidth: 100
endOfLine: "lf"
semi: true
bracketSpacing: true
overrides:
  - files: "*.java"
    options:
      tabWidth: 4
  - files: "*.html"
    options:
      tabWidth: 4
plugins:
  - "@prettier/plugin-xml"
  - "prettier-plugin-java"
  - "prettier-plugin-properties"
