# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  node: system
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [commit, manual]
      - id: check-yaml
        stages: [commit, manual]
      - id: check-added-large-files
        stages: [commit, manual]
      - id: check-merge-conflict
        stages: [commit, manual]
      - id: check-vcs-permalinks
        stages: [commit, manual]
      - id: no-commit-to-branch
        stages: [commit, manual]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg, manual]
  - repo: https://github.com/DavidFederl/pre-commit-prettier.git
    rev: v0.2.0
    hooks:
      - id: prettier
        stages: [commit, manual]
      - id: prettier-java
        stages: [commit, manual]
      - id: prettier-config
        stages: [commit, manual]
