services:
  broker:
    image: hivemq/hivemq-ce:2023.4
    restart: always
    environment:
      - HIVEMQ_LOG_LEVEL=ERROR
    networks:
      - elastic-ai-network
    ports:
      - "1883:1883"

  monitor:
    image: ghcr.io/es-ude/elastic-ai.monitor:latest
    restart: always
    depends_on:
      - broker
    networks:
      - elastic-ai-network
    ports:
      - "8081:8081"
    environment:
      - HOST_IP=${HOST_IP}
    command:
      - "-b"
      - "broker"
      - "-p"
      - "1883"

  enV5-twin:
    image: ghcr.io/es-ude/elastic-ai.runtime:latest
    restart: always
    depends_on:
      - broker
      - monitor
    networks:
      - elastic-ai-network
    command:
      - "-b"
      - "broker"
      - "-p"
      - "1883"

networks:
  elastic-ai-network:
    external: false
    name: elastic-ai-network
