# start with 'docker compose -d up'
# stop with 'docker compose down'

# !! Adjust the camera ip to your liking !!
# Recorded Values can be found under './SensorValues/'

services:
  broker:
    image: hivemq/hivemq-ce:2023.4
    restart: always
    environment:
      - HIVEMQ_LOG_LEVEL=ERROR
    networks:
      - elastic-ai-network
    ports:
      - "1883:1883"

  monitor:
    image: ghcr.io/es-ude/elastic-ai.cloud.applications.monitor:latest
    restart: always
    depends_on:
      - broker
    networks:
      - elastic-ai-network
    ports:
      - "8080:80"
    environment:
      - HOST_IP=${HOST_IP}
    command:
      - "--broker-address"
      - "broker"

  ball_challenge:
    image: ghcr.io/es-ude/elastic-ai.cloud.applications.ball_challenge:latest
    restart: always
    depends_on:
      - broker
    volumes:
      - ./SensorValues:/SensorValues
    networks:
      - elastic-ai-network
    ports:
      - "8081:80"
    environment:
      - HOST_IP=${HOST_IP}
    command:
      - "--broker-address"
      - "broker"
      - "--camera-address"
      - "127.0.0.1"

networks:
  elastic-ai-network:
    external: false
    name: elastic-ai-network
