---
apiVersion: v1
kind: Service
metadata: 
    name: monitoring-service
spec:
    selector: 
        app: monitoring-service
    ports:
    - name: monitoring-port
      port: 8081
      protocol: TCP
      nodePort: 30134
    type: NodePort
