---
apiVersion: v1
kind: Service
metadata: 
    name: hive-mq
spec:
    selector: 
      app: hive-mq
    ports:
    - name: mqtt-port
      port: 1883
      protocol: TCP
      nodePort: 30135
    type: NodePort
