= How to contribute
:toc:
:toclevels: 3
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

== Naming Scheme

[cols=">h,<"]
|===
| Scope | Scheme

| Files
| PascalCase

| Class
| PascalCase

| Functions
| camelCase

| Variables
| camelCase

| Constants
| SCREAMING_SNAKE_CASE
|===

== Code Contributions

[IMPORTANT]
====
Don’t push directly to the `main` branch::
- Push your modification to a new branch
- Open a pull request to `main`
- The maintainer of the repository can then merge your modifications into the existing codebase
====

== Workflow

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
----
gitGraph
    commit
    commit
    branch xxx-feature
    commit
    commit
    checkout main
    branch yyy-feature
    commit
    checkout main
    merge xxx-feature
    commit
    commit
    merge yyy-feature
    checkout main
----

NOTE: If you want to develop a new feature, or contribute new source code, you are required branch out from the develop branch with your own feature branch This branch will then be merged back into the develop branch via a Pull-Request.

[#_commit_messages]
== Commit Messages

We use https://spin.atomicobject.com/conventional-commits/[conventional commits]

NOTE: To ensure our guidelines we suggest to use Pre-Commit linke it is described in the link:../SETUP_GUIDE.adoc#_pre_commit_optional[Setup Guide].
