= DEMO
:toc:
:toclevels: 3
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

For running the DEMO, four parts are needed.
An MQTT Broker, the Monitor, the EnV5 Twin, and an EnV5 Device.

The three software parts can be started together by using the provided link:../compose.yaml[docker compose file].
For this, the Twin and Monitor docker images need to be built beforehand (See link:../README.adoc#_build_docker_container[README]).

[source,bash]
----
docker compose up
----

== Communication

The diagrams show simplified, how the parties communicate with each other in the DEMO.

=== Status

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant communicationEndpoint as enV5Twin
    participant device as enV5
    participant monitorCommunicationEndpoint as Monitor
    participant broker as Broker

    communicationEndpoint ->> broker: STATUS
    device ->> broker: STATUS
    monitorCommunicationEndpoint ->> broker: STATUS
    broker ->> monitorCommunicationEndpoint: EnV5Twin STATUS

    broker ->> communicationEndpoint: Env5 STATUS
    communicationEndpoint ->> broker: UPDATED STATUS

    broker ->> monitorCommunicationEndpoint: EnV5Twin STATUS
....

=== DATA

NOTE: Broker removed for simplicity

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant monitorCommunicationEndpoint as Monitor
    participant communicationEndpoint as enV5Twin
    participant device as enV5

    monitorCommunicationEndpoint ->> communicationEndpoint: START
    communicationEndpoint ->> device: START

    device ->> communicationEndpoint: DATA
    communicationEndpoint ->> monitorCommunicationEndpoint: DATA

    monitorCommunicationEndpoint ->> communicationEndpoint: STOP
    communicationEndpoint ->> device: STOP
....

=== FLASH

NOTE: Broker removed for simplicity

ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant monitorCommunicationEndpoint as Monitor
    participant communicationEndpoint as enV5Twin
    participant device as enV5

    monitorCommunicationEndpoint ->> communicationEndpoint: FLASH
    communicationEndpoint ->> device: FLASH

    device ->> monitorCommunicationEndpoint: REQUEST
    monitorCommunicationEndpoint ->> device: BITFILE

    device ->> communicationEndpoint: DONE
    communicationEndpoint ->> monitorCommunicationEndpoint: DONE
....
