= EIP Protocol (v0.2)
:toc:
:toclevels: 3
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

[.lead]
The eip protocol provides a specification of a pub-sub-protocol.
Typically, this will be implemented via MQTT, but this is *not* fixed.
The basic functionalities provided are _subscribing_,
_unsubscribing_ and _publishing_ to and from topics and topic filters,
together with a keepalive mechanism with last will message.

== Message

A message consists of a topic combined with a payload/data that should be published to the given topic.

=== Topic

A topic is constructed as followed:

[source,text]
----
eip://<broker_domain>/<object_id>/<message_type>/<type_dependent>
----
object_id::
    The individual identifier of the target (Receiver) or the Sender
message_type::
    It Is defined as in the part <<#_message_types,Message Types>>.
type_dependent::
    Subtopics depending on the message type.
    For example, for different sensor values.

[#_message_types]
=== Message Types

[cols=">h,<,<", stripes=hover]
|===
| Type | Object | Description

| STATUS
| Sender
| a message containing the online(1)/offline(0) status of an object

| START
| Receiver
| a message requesting an object to start sending a stream of data

| STOP
| Receiver
| a message requesting an object to stop sending a stream of data

| DATA
| Sender
| a message containing data

| DO
| Receiver
| a message containing a command

| DONE
| Sender
| a message containing the response to a DO message
|===

==== STATUS

Topic::
    `eip://<broker_domain>/<object_id>/STATUS`

Data::
    <key>:<value>;<key>:<value>;...

Mandatory Data::
    * ID:<object_id>;
    * TYPE:<object_type>;
    * STATE:<ONLINE/OFFLINE>;

Optional Data::
    * DATA:<List of Data that can be requested, seperated by ",">;
    * Other optional information with '<key>:<value>;', example: 'VERSION:<Software version on the client>;'

Information::
    * The retain-flag of this message should be set to assure status discovery for newly entered participants!
    * The offline message should be automatically sent by the broker after a connection loss (LWT message).
    * The online message should only be sent by a new hardware device or Application client.
    * Each part of the data consists of `<DATA-TYP>:<DATA>;`, the order is arbitrary

Example message::
--
[source,text]
----
msg("eip://uni-due.de/es/client1/STATUS","ID:client1;TYPE:enV5;STATE:ONLINE") <1>
msg("eip://uni-due.de/es/client1/STATUS","ID:client1;TYPE:enV5;STATE:OFFLINE") <2>
----
<1> Online Message
<2> Offline Message (LWT)
--

.Communication Specification
ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant m as Monitorclient
    participant t as client for Device
    participant b as Broker
    participant d as Device

    m ->> b: sub("eip://<broker_domain>/+/STATUS")
    Note over b,d: ESTABLISH CONNECTION
    d ->> b: pub("eip://<broker_domain>/env5_1/STATUS","env5_1#59;1")
    b ->> m: ("eip://<broker_domain>/env5_1/STATUS","env5_1#59;1")
    m -) t: start communicationEndpoint
    activate t
    Note over m,d: ...
    Note over d: LOST CONNECTION
    b ->> m: ("eip://<broker_domain>/env5_1/STATUS","env5_1#59;0")
    m -) t: stop communicationEndpoint
    deactivate t
....

==== START

Topic::
    `eip://<broker_domain>/<object_id>/START/<data_id>`

Data::
    topic specifying `eip://<broker_domain>/<object_id>` that is interested in data

Example message::
--
[source,text]
----
msg("eip://uni-due.de/es/client1/START/light","eip://uni-due.de/es/client2")
----
--

==== STOP

Topic::
    `eip://<broker_domain>/<object_id>/STOP/<data_id>`

Data::
    topic specifying `eip://<broker_domain>/<object_id>` that was interested in data

Example message::
--
[source,text]
----
msg("eip://uni-due.de/es/client1/STOP/light","eip://uni-due.de/es/client2")
----
--

==== DATA

Topic::
    `eip://<broker_domain>/<object_id>/DATA/<data_id>`

Data::
    value encoded as a string

INFO::
    Interested nodes can subscribe to this topic to receive new data

Example message::
--
[source,text]
----
msg("eip://uni-due.de/es/client1/DATA/light","30.7")
----
--

.Communication specification for data that is published *continuously*
ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant t1 as client 1
    participant t2 as client 2
    participant b as Broker
    participant d as Device

    t2 ->> b: pub("eip://<broker_domain>/client2/DATA/d1", "<val>")
    t1 ->> b: sub("eip://<broker_domain>/client2/DATA/d1")
    t2 ->> b: pub("eip://<broker_domain>/client2/DATA/d1", "<val>")
    b ->> t1: ("eip://<broker_domain>/client2/DATA/d1", "<val>")
    t2 ->> b: pub("eip://<broker_domain>/client2/DATA/d1", "<val>")
    b ->> t1: ("eip://<broker_domain>/client2/DATA/d1", "<val>")
....

.Communication for data that has to be *requested*
ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant t1 as client 1
    participant t2 as client 2
    participant b as Broker
    participant d as Device

      t1 ->> b: sub("eip://<broker_domain>/client2/DATA/d1")
    t1 ->> b: pub("eip://<broker_domain>/client2/START/d1","eip://<broker_domain>/client1")
    b ->> t2: ("eip://<broker_domain>/client2/START/d1","eip://<broker_domain>/client1")
    t2 ->> b: sub("eip://<broker_domain>/client1/STATUS")
    Note over t2,d: REQUEST DATA FROM DEVICE
    Note over t2: START SENDING DATA
    t2 ->> b: pub("eip://<broker_domain>/client2/DATA/d1","<val>")
    b ->> t1: ("eip://<broker_domain>/client2/DATA/d1","<val>")
    Note over t1,b: ...
    alt client 1 send STOP
    t1 ->> b: pub("eip://<broker_domain>/client2/STOP/d1","eip://<broker_domain>/client1")
    b ->> t2: ("eip://<broker_domain>/client2/STOP/d1","eip://<broker_domain>/client1")
    else client 1 lost connection
    Note over t1: LOST CONNECTION
    b ->> t2: ("eip://<broker_domain>/client1/STATUS","0")
    end
    Note over t2: STOP SENDING DATA
    t2 ->> b: unsub("eip://<broker_domain>/client1/STATUS")
....

==== DO

Topic::
    `eip://<broker_domain>/<object_id>/DO/<command>`

Data::
    command specific

Example message::
--
[source,text]
----
msg("eip://uni-due.de/es/client1/DO/SET/led/1","1")
----
--

.Communication specification for a command *without* response
ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant t1 as client 1
    participant t2 as client 2
    participant b as Broker
    participant d as Device

    t2 ->> b: sub("eip://<broker_domain>/client2/DO/<cmd1>")
    t1 ->> b: pub("eip://<broker_domain>/client2/DO/<cmd1>","<val>")
    b ->> t2: ("eip://<broker_domain>/client2/DO/<cmd1>","<val>")
    Note over t2,d: EXECUTE COMMAND
....

==== DONE

Topic::
    `eip://<broker_domain>/<object_id>/DONE/<command>`

Data::
    command specific

Example message::
--
[source,text]
----
msg("eip://uni-due.de/es/client1/DONE/SET/led/1","1")
----
--

.Communication specification for a command *with* response
ifdef::env-github[]
[source,mermaid]
endif::[]
ifndef::env-github[]
[mermaid]
endif::[]
....
sequenceDiagram
    participant t1 as client 1
    participant t2 as client 2
    participant b as Broker
    participant d as Device

    t2 ->> b: sub("eip://<broker_domain>/client2/DO/<cmd1>")
    t1 ->> b: sub("eip://<broker_domain>/client2/DONE/<cmd1>")
    t1 ->> b: pub("eip://<broker_domain>/client2/DO/<cmd1>","<val>")
    b ->> t2: ("eip://<broker_domain>/client2/DO/<cmd1>","<val>")
    Note over t2,d: EXECUTE COMMAND
    alt successful
    t2 ->> b: pub("eip://<broker_domain>/client2/DONE/<cmd1>","<success>")
    b ->> t1: ("eip://<broker_domain>/client2/DONE/<cmd1>","<success>")
    else unsuccessful
    t2 ->> b: pub("eip://<broker_domain>/client2/DONE/<cmd1>","<failed>")
    b ->> t1: ("eip://<broker_domain>/client2/DONE/<cmd1>","<failed>")
    end
....
