name: "Beautify"
on:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # Install java plugin for Prettier
          prettier_plugins: prettier-plugin-java
          # Apply prettier to java and markdown files
          prettier_options: "--write **/*.{java,md}"
          # Use Commitlint bases commit message
          commit_message: "style(prettier): beautify code"
