name: "Build Container Image"
on:
  workflow_dispatch:
  release:
    types:
      - published
      
jobs:
  docker_image:
    name: Genrate Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Release
        uses: GuillaumeFalourd/get-release-or-tag@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Docker Image
        run: ./gradlew jibDockerBuild
      - name: Tag Runtime
        run: |
          docker tag runtime:latest ghcr.io/DavidFederl/elastic-ai.runtime:latest
          docker tag runtime:latest ghcr.io/DavidFederl/elastic-ai.runtime:${{ steps.Release.outputs.tag }}
      - name: Tag Monitor
        run: |
          docker tag monitor:latest ghcr.io/DavidFederl/elastic-ai.monitor:latest
          docker tag monitor:latest ghcr.io/DavidFederl/elastic-ai.monitor:${{ steps.Release.outputs.tag }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Runtime to Github Container Registry
        run: docker push --all-tags ghcr.io/es-ude/elastic-ai.runtime:latest
      - name: Push Monitor to Github Container Registry
        run: docker push --all-tags ghcr.io/es-ude/elastic-ai.monitor:latest
