# Workflow requires Variables to be defined as follows:
#   GHCR_NAMESPACE    -> repository name
#   GHCR_USER         -> User to push to GHCR with GITHUB_TOKEN
#   GHCR_ACCESS_TOKEN -> Password for GHCR_USER
#   GITHUB_TOKEN has to have write permission !!

name: "Build Container Image"
on:
  workflow_dispatch:
  release:
    types:
      - published
      
jobs:
  docker_image:
    name: Genrate Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get Release
        id: release
        uses: GuillaumeFalourd/get-release-or-tag@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Docker Image
        run: ./gradlew jibDockerBuild
      - name: Tag Runtime
        run: |
          docker tag runtime:latest ghcr.io/${{ vars.GHCR_NAMESPACE }}/elastic-ai.runtime:latest
          docker tag runtime:latest ghcr.io/${{ vars.GHCR_NAMESPACE }}/elastic-ai.runtime:${{ steps.release.outputs.tag }}
      - name: Tag Monitor
        run: |
          docker tag monitor:latest ghcr.io/${{ vars.GHCR_NAMESPACE }}/elastic-ai.monitor:latest
          docker tag monitor:latest ghcr.io/${{ vars.GHCR_NAMESPACE }}/elastic-ai.monitor:${{ steps.release.outputs.tag }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Push Runtime to Github Container Registry
        run: docker push --all-tags ghcr.io/${{ vars.GHCR_NAMESPACE }}/elastic-ai.runtime
      - name: Push Monitor to Github Container Registry
        run: docker push --all-tags ghcr.io/${{ vars.GHCR_NAMESPACE }}/elastic-ai.monitor
