name: Apply Code Formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # Install java plugin for Prettier
          prettier_plugins: prettier-plugin-java
          # Apply prettier to java and markdown files
          prettier_options: "--write **/*.{java,md}"
